In [ ]:
# Customer Segmentation

## Veltrix RevOps Intelligence

This notebook segments customers based on customer health scores.

### Objectives
- Identify high-risk customers
- Classify customer health
- Support retention initiatives
- Improve customer success operations

In [1]:
import pandas as pd
import numpy as np

print("Customer Segmentation Notebook Loaded Successfully")

Customer Segmentation Notebook Loaded Successfully

In [2]:
customers = pd.DataFrame({
    'customer_id':[101,102,103,104,105,106],
    'customer_health_score':[95,82,67,48,73,35]
})

customers

   customer_id  customer_health_score
0          101                     95
1          102                     82
2          103                     67
3          104                     48
4          105                     73
5          106                     35

In [3]:
customers['health_segment'] = pd.cut(
    customers['customer_health_score'],
    bins=[0,50,75,100],
    labels=['At Risk','Moderate','Healthy']
)

customers

   customer_id  customer_health_score health_segment
0          101                     95        Healthy
1          102                     82        Healthy
2          103                     67       Moderate
3          104                     48        At Risk
4          105                     73       Moderate
5          106                     35        At Risk

In [4]:
customers['health_segment'].value_counts()

health_segment
At Risk     2
Moderate    2
Healthy     2
Name: count, dtype: int64

In [5]:
segment_summary = customers.groupby(
    'health_segment',
    observed=False
).agg({
    'customer_id':'count',
    'customer_health_score':'mean'
})

segment_summary

                customer_id  customer_health_score
health_segment
At Risk                   2                   41.5
Moderate                  2                   70.0
Healthy                   2                   88.5